#!/bin/bash
echo "╭───────────────────────────╮"
echo "│         PILIH MENU        │"
echo "│           VLESS           │"
echo "╰───────────────────────────╯"
echo ""
echo "+----+----------------------+"
echo "|    |        MENU          |"
echo "+----+----------------------+"
echo "|  1 | Tambah akun          |"
echo "|  2 | Hapus akun           |"
echo "|  3 | Cek akun             |"
echo "|  4 | Kembali              |"
echo "+----+----------------------+"
echo ""
read -p "Masukkan pilihan (1-4): " pilih

# Cek input pengguna menggunakan perintah case
case "$pilih" in
  1) clear&&add-vless ;;
  2) clear&&del-vless ;;
  3) clear&&chk-vless ;;
  4) clear&&menu ;;
  "")
      clear&&menu-vless ;;
  *)
      clear
      echo "Pilihan tidak valid. Silakan masukkan angka 1-4."
      menu-vless ;;
esac
