#!/bin/bash
clear
# Assign system information to variables
OS=$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d \")
RAM=$(free -h | grep Mem | awk '{printf "%-10s / %-10s", $2, $4}')
CPU=$(grep -c processor /proc/cpuinfo)" Core(s)"
UPTIME=$(uptime -p)
TIME=$(date +"%A, %d %B %Y %T %Z")

# Assign network information to variables
ISP=$(curl -s https://ipapi.co/org/)
CITY=$(curl -s https://ipapi.co/city/)
IP=$(curl -s https://ipapi.co/ip/)
DOMAIN=$(cat /etc/v2ray/domain.txt)
#check status service
stat_vmess=$(systemctl is-active --quiet v2ray && echo "active" || echo "inactive")
stat_vless=$(systemctl is-active --quiet v2ray@vless && echo "active" || echo "inactive")
stat_trojan=$(systemctl is-active --quiet v2ray@trojan && echo "active" || echo "inactive")
#check total user
usr_trojan=$(grep -c 'utag' /etc/v2ray/config/trojan.json)
#usr_vless=$(grep -c 'utag' /etc/v2ray/config/vless.json)
usr_vless=$(($(grep -c 'utag' /etc/v2ray/config/vless.json)/2))
usr_vmess=$(($(grep -c 'utag' /etc/v2ray/config/config.json)/2))

# Display system information in a formatted table
printf "╭───────────────────────────────────────────────────────────────╮\n"
printf "│                       INFORMASI SISTEM                        │\n"
printf "│                                                               │\n"
printf "│ OS       : %-50s │\n" "$OS"
printf "│ RAM      : %-50s │\n" "$RAM"
printf "│ CPU      : %-50s │\n" "$CPU"
printf "│ Uptime   : %-50s │\n" "$UPTIME"
printf "│ Time     : %-50s │\n" "$TIME"
printf "│                                                               │\n"
printf "╰───────────────────────────────────────────────────────────────╯\n\n"

# Display network information in a formatted table
printf "╭───────────────────────────────────────────────────────────────╮\n"
printf "│                      INFORMASI JARINGAN                       │\n"
printf "│                                                               │\n"
printf "│ City     : %-50s │\n" "$CITY"
printf "│ ISP      : %-50s │\n" "$ISP"
printf "│ IP       : %-50s │\n" "$IP"
printf "│ DOMAIN   : %-50s │\n" "$DOMAIN"
printf "╰───────────────────────────────────────────────────────────────╯\n\n"
# Display menu options
printf "╭───────────╮\n"
printf "│  PILIHAN  │\n"
printf "╰───────────╯\n"
printf "╭───────────────────────────────────╮\n"
printf "│              SERVICE              │\n"
printf "│───────────────────────────────────│\n"
printf "│                                   │\n"
printf "│  VMess   : %-10s | %d users   │\n" "$stat_vmess" "$usr_vmess"
printf "│  VLESS   : %-10s | %d users   │\n" "$stat_vless" "$usr_vless"
printf "│  Trojan  : %-10s | %d users   │\n" "$stat_trojan" "$usr_trojan"
printf "│───────────────────────────────────│\n"
printf "│               MENU                │\n"
printf "│───────────────────────────────────│\n"
printf "│ [1] Menu vmess  | [5] Keluar      │\n"
printf "│ [2] Menu vless  |                 │\n"
printf "│ [3] Menu trojan |                 │\n"
printf "│ [4] Speedtest   |                 │\n"
printf "╰───────────────────────────────────╯\n\n"
read -p "Masukkan pilihan (1-5): " pilih
case "$pilih" in
  1) clear&&menu-vmess ;;
  2) clear&&menu-vless ;;
  3) clear&&menu-trojan ;;
  4) clear&&speedtest ;;
  5) echo "Sayonaraaa!"; exit 0 ;;
  "")
      clear&&menu ;;
  *)
      clear
      echo "Pilihan tidak valid. Silakan masukkan angka 1-4."
      menu ;;
esac