#!/bin/bash
clear
echo "╭───────────────────────────╮"
echo "│         PILIH MENU        │"
echo "│           VLESS           │"
echo "╰───────────────────────────╯"
echo ""
echo "+----+----------------------+"
echo "|    |        MENU          |"
echo "+----+----------------------+"
echo "|  1 | Tambah akun          |"
echo "|  2 | Hapus akun           |"
echo "|  3 | Cek akun             |"
echo "|  4 | Kembali              |"
echo "+----+----------------------+"
echo ""
read -p "Masukkan pilihan (1-4): " pilih

# Cek input pengguna menggunakan perintah case
case "$pilih" in
  1) add-vless ;;
  2) del-vless ;;
  3) chk-vless ;;
  4) menu ;;
  "")
      menu-vless ;;
  *)
      echo "Pilihan tidak valid. Silakan masukkan angka 1-4."
      bash menu-vless.sh ;;
esac
